feeder: dataloader_video.BaseFeeder
phase: train
dataset: CSL-Daily
# phoenix2014-T
# CSL-Daily

work_dir: ./work_dirt/
batch_size: 4
random_seed: 0 
test_batch_size: 4
num_worker: 10
device: 0
log_interval: 10000
eval_interval: 1
save_interval: 10
 
loss_weights:
  SeqCTC: 1.0 
  ConvCTC: 1.0
  Dist: 25.0
  Cu: 0.0005
  Cp: 0.0005
load_weights:  False
load_checkpoints: False
optimizer_args:
  optimizer: Adam
  # for phoenix2014-T
  # learning_rate:
  #   base_lr: 1.0e-06
  #   mapper: 0.001
  #   translation: 1.0e-06

  # for csl-daily
  learning_rate:
    base_lr: 1.0e-05
    mapper: 0.001
    translation: 1.0e-05
  step: [40, 60]
  learning_ratio: 1
  scheduler: consine   #ScheaL #consine
  weight_decay: 0.001
  start_epoch: 0
  num_epoch: 30 #50
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0  # 0-1 represents ratio, >1 represents absolute value
  input_size: 224

model: slr_network.SLRModel
decode_mode: beam
model_args:
  num_classes: 1116  #2001  #1116
  c2d_type: resnet34 # resnet18
  conv_type: 2
  use_bn: 1 
  share_classifier: True
  weight_norm: True
